---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8000}]
  - ["forwarded_port", {guest: 8080, host: 8080}]

  driver_config:
    require_chef_omnibus: 11.12.8

provisioner:
  name: chef_zero
  client_rb:
    environment: demo
  attributes:
    holland:
      enabled: false
    mysql-multi:
      master: '127.0.0.1'
    cloud:
      public_ipv4: '127.0.0.1'
    platformstack:
      cloud_backup:
        enabled: false
      cloud_monitoring:
        enabled: false
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    rackspace:
      cloud_credentials:
        username: 'racker'
        api_key: 'secret'
    mysql:
      server_root_password: 'randompass'
      server_repl_password: 'randompass'
      server_debian_password: 'randompass'
    nodestack:
      app_db_user_password: 'randompass'
      binary_path: '/usr/local/bin/node'
    nodejs:
      install_method: 'binary'

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]
  - name: centos-7.0
    run_list:
    - recipe[yum]

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags'
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[nodestack::demo]
      - recipe[nodestack::application_nodejs]
