---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  client_rb:
    environment: demo
  attributes:
    holland:
      enabled: false
    mysql-multi:
      master: '127.0.0.1'
    cloud:
      public_ipv4: '127.0.0.1'
    platformstack:
      elkstack_logging:
        enabled: false
      cloud_backup:
        enabled: false
      cloud_monitoring:
        enabled: false
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    rackspace:
      cloud_credentials:
        username: 'racker'
        api_key: 'secret'
    mysql:
      server_root_password: 'randompass'
      server_repl_password: 'randompass'
      server_debian_password: 'randompass'
    nodestack:
      app_db_user_password: 'randompass'
      binary_path: '/usr/local/bin/node'
    nodejs:
      install_method: 'binary'

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.6
    run_list:
    - recipe[yum]
<% if ENV['CI'] %>
  - name: centos-7 # kitchen-rackspace
<% else %>
  - name: centos-7.0 # kitchen-vagrant
<% end %>
    run_list:
    - recipe[yum]

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags'
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[nodestack::demo]
      - recipe[nodestack::application_nodejs]
      - recipe[nodestack::nginx]
